import BoulderKit
import Foundation
import Supabase

/// Routesetter and manager operations on sectors and problems.
extension Backend {
    /// Uploads a JPEG into `sector-photos` and returns the object path.
    func uploadSectorPhoto(gymId: UUID, sectorId: UUID, jpeg: Data) async throws -> String {
        let path = [gymId, sectorId, UUID()].map { $0.uuidString.lowercased() }.joined(separator: "/") + ".jpg"
        _ = try await client.storage
            .from(AppConfig.sectorPhotosBucket)
            .upload(path, data: jpeg, options: FileOptions(contentType: "image/jpeg"))
        return path
    }

    @discardableResult
    func resetSector(
        sectorId: UUID,
        expectedPhotoId: UUID?,
        storagePath: String,
        width: Int,
        height: Int,
        removeProblemIds: [UUID],
        note: String?
    ) async throws -> UUID {
        struct Params: Encodable, Sendable {
            let p_sector_id: UUID
            let p_expected_photo_id: UUID?
            let p_storage_path: String
            let p_width: Int
            let p_height: Int
            let p_remove_problem_ids: [UUID]
            let p_note: String?

            enum CodingKeys: String, CodingKey {
                case p_sector_id, p_expected_photo_id, p_storage_path, p_width, p_height
                case p_remove_problem_ids, p_note
            }

            // Nulls must be sent explicitly so PostgREST matches the signature.
            func encode(to encoder: Encoder) throws {
                var container = encoder.container(keyedBy: CodingKeys.self)
                try container.encode(p_sector_id, forKey: .p_sector_id)
                try container.encode(p_expected_photo_id, forKey: .p_expected_photo_id)
                try container.encode(p_storage_path, forKey: .p_storage_path)
                try container.encode(p_width, forKey: .p_width)
                try container.encode(p_height, forKey: .p_height)
                try container.encode(p_remove_problem_ids, forKey: .p_remove_problem_ids)
                try container.encode(p_note, forKey: .p_note)
            }
        }
        return try await client.rpc("reset_sector", params: Params(
            p_sector_id: sectorId,
            p_expected_photo_id: expectedPhotoId,
            p_storage_path: storagePath,
            p_width: width,
            p_height: height,
            p_remove_problem_ids: removeProblemIds,
            p_note: note
        ))
        .execute()
        .value
    }

    /// Idempotent: `problemId` is generated by the app, a retry returns it again.
    @discardableResult
    func addProblem(
        problemId: UUID,
        sectorId: UUID,
        expectedPhotoId: UUID,
        pinX: Double,
        pinY: Double,
        draft: ProblemDraft
    ) async throws -> UUID {
        struct Params: Encodable, Sendable {
            let p_sector_id: UUID
            let p_expected_photo_id: UUID
            let p_pin_x: Double
            let p_pin_y: Double
            let p_grade_id: UUID
            let p_hold_color: HoldColor
            let p_style_tags: [StyleTag]
            let p_name: String?
            let p_problem_id: UUID

            enum CodingKeys: String, CodingKey {
                case p_sector_id, p_expected_photo_id, p_pin_x, p_pin_y, p_grade_id
                case p_hold_color, p_style_tags, p_name, p_problem_id
            }

            func encode(to encoder: Encoder) throws {
                var container = encoder.container(keyedBy: CodingKeys.self)
                try container.encode(p_sector_id, forKey: .p_sector_id)
                try container.encode(p_expected_photo_id, forKey: .p_expected_photo_id)
                try container.encode(p_pin_x, forKey: .p_pin_x)
                try container.encode(p_pin_y, forKey: .p_pin_y)
                try container.encode(p_grade_id, forKey: .p_grade_id)
                try container.encode(p_hold_color, forKey: .p_hold_color)
                try container.encode(p_style_tags, forKey: .p_style_tags)
                try container.encode(p_name, forKey: .p_name)
                try container.encode(p_problem_id, forKey: .p_problem_id)
            }
        }
        guard let gradeId = draft.gradeId else { throw ProblemDraft.MissingGrade() }
        return try await client.rpc("add_problem", params: Params(
            p_sector_id: sectorId,
            p_expected_photo_id: expectedPhotoId,
            p_pin_x: pinX,
            p_pin_y: pinY,
            p_grade_id: gradeId,
            p_hold_color: draft.color,
            p_style_tags: draft.styleTags.sorted { $0.rawValue < $1.rawValue },
            p_name: draft.trimmedName,
            p_problem_id: problemId
        ))
        .execute()
        .value
    }

    func updateProblem(problemId: UUID, draft: ProblemDraft) async throws {
        struct Changes: Encodable, Sendable {
            let grade_id: UUID
            let hold_color: HoldColor
            let style_tags: [StyleTag]
            let name: String?

            enum CodingKeys: String, CodingKey {
                case grade_id, hold_color, style_tags, name
            }

            func encode(to encoder: Encoder) throws {
                var container = encoder.container(keyedBy: CodingKeys.self)
                try container.encode(grade_id, forKey: .grade_id)
                try container.encode(hold_color, forKey: .hold_color)
                try container.encode(style_tags, forKey: .style_tags)
                try container.encode(name, forKey: .name)
            }
        }
        guard let gradeId = draft.gradeId else { throw ProblemDraft.MissingGrade() }
        try await client.from("problems")
            .update(Changes(
                grade_id: gradeId,
                hold_color: draft.color,
                style_tags: draft.styleTags.sorted { $0.rawValue < $1.rawValue },
                name: draft.trimmedName
            ), returning: .minimal)
            .eq("id", value: problemId)
            .execute()
    }

    func moveProblemPin(problemId: UUID, pinX: Double, pinY: Double) async throws {
        struct Params: Encodable, Sendable {
            let p_problem_id: UUID
            let p_pin_x: Double
            let p_pin_y: Double
        }
        try await client.rpc("move_problem_pin", params: Params(p_problem_id: problemId, p_pin_x: pinX, p_pin_y: pinY)).execute()
    }

    func setProblemRemoved(problemId: UUID, removed: Bool) async throws {
        struct Params: Encodable, Sendable {
            let p_problem_id: UUID
            let p_removed: Bool
        }
        try await client.rpc("set_problem_removed", params: Params(p_problem_id: problemId, p_removed: removed)).execute()
    }
}

/// What a routesetter fills in for a problem.
struct ProblemDraft: Equatable, Sendable {
    struct MissingGrade: LocalizedError {
        var errorDescription: String? { "Wybierz wycenę problemu." }
    }

    var gradeId: UUID?
    var color: HoldColor = .yellow
    var styleTags: Set<StyleTag> = []
    var name = ""

    var trimmedName: String? {
        let value = name.trimmingCharacters(in: .whitespacesAndNewlines)
        return value.isEmpty ? nil : value
    }

    init() {}

    init(problem: ActiveProblem) {
        gradeId = problem.gradeId
        color = problem.holdColor
        styleTags = Set(problem.styleTags)
        name = problem.name ?? ""
    }
}
